### ISSUE TITLE
Somthing went wrong

### ISSUE THREAD

**Issue by pro-spild** [fedebotu/clone-anonymous-github#4]
I used your repository to download the code for a paper, but something went wrong, it seems not work well.
My URL is : https://anonymous.4open.science/r/MobiCom-RFID-Counting-1008/
floder path is D:/Code/python/RFID/
The content of DEBUG Windows is:
    During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\threading.py", line 1009, in _bootstrap_inner
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\src\utils.py", line 34, in run
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\src\download.py", line 77, in download_repo
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\requests\api.py", line 73, in get
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\requests\api.py", line 59, in request
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\requests\sessions.py", line 587, in request
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\requests\sessions.py", line 701, in send
  File "C:\Users\Host\AppData\Local\Temp\ONEFIL~1\requests\adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='anonymous.4open.science', port=443): Max retries exceeded with url: /api/repo/MobiCom-RFID-Counting-1008/files/ (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))

**Comment by fedebotu** [comment]
Hi, this happened to me as well. If you download too many files, then your IP will get banned. The best way to circumvent this is to upload a zip file instead - that will count as one single download, and you won't get blocked. 
Otherwise, you would have to implement some proxy rotation I guess in order to avoid the blockage 🤔

**Comment by pro-spild** [comment]
> Hi, this happened to me as well. If you download too many files, then your IP will get banned. The best way to circumvent this is to upload a zip file instead - that will count as one single download, and you won't get blocked. Otherwise, you would have to implement some proxy rotation I guess in order to avoid the blockage 🤔

thats ok.Thanks for your relpy
